version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-management
    ports:
      - "15432:5432"
    volumes:
      - ./backend/e2e/seed.sql:/docker-entrypoint-initdb.d/00_seed.sql
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U postgres -d user-management"]
      test:
        [
          "CMD-SHELL",
          'psql -h localhost -U postgres -d user-management -qtAX -c "SELECT 1 FROM information_schema.tables WHERE table_schema = ''public'' AND table_name = ''your_table_name_from_seed_sql'' LIMIT 1;" | grep -q 1 || exit 1',
        ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=8080
    command:
      [
        "./userapi",
        "--dsn",
        "postgresql://postgres:postgres@postgres:5432/user-management?sslmode=disable&timeout=5s",
      ]
    ports:
      - "8081:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/app/usercli db ping --dsn=postgresql://postgres:postgres@postgres:5432/user-management?sslmode=disable&timeout=5s",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backendjs:
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=8080
      - DSN=postgresql://postgres:postgres@postgres:5432/user-management?sslmode=disable&timeout=5s
    ports:
      - "8082:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'wget --quiet --spider --tries=1 --timeout=5 --header="Content-Type: application/json" http://localhost:8080/api/v1/status || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_healthy
