version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-management
    ports:
      - "15432:5432"
    volumes:
      - ./backend/tests/seed.sql:/docker-entrypoint-initdb.d/00_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=7001
    command:
      [
        "./userapi",
        "--dsn",
        "postgresql://postgres:postgres@postgres:5432/user-management?sslmode=disable&timeout=5s",
      ]
    ports:
      - "7001:7001"
