-- Create users table
CREATE TABLE IF NOT EXISTS users (
    -- consider to use UUID v7, UUIDs are a better choice to prevent:
    -- ID enumeration attacks, data scraping, IDOR vulnerabilities, and competitor intelligence gathering.
    user_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    user_status VARCHAR(1) NOT NULL CHECK (user_status IN ('A', 'I', 'T')),
    department VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create trigger function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.updated_at IS NULL THEN
        NEW.updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger on users table
CREATE OR REPLACE TRIGGER update_users_modtime
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- Insert 15 random users
BEGIN;
DELETE FROM users;
INSERT INTO users (user_name, first_name, last_name, email, user_status, department) VALUES
('jsmith', 'John', 'Smith', 'john.smith@example.com', 'A', 'Engineering'),
('mjohnson', 'Mary', 'Johnson', 'mary.johnson@example.com', 'A', 'Marketing'),
('rwilliams', 'Robert', 'Williams', 'robert.williams@example.com', 'A', 'Finance'),
('pjones', 'Patricia', 'Jones', 'patricia.jones@example.com', 'I', 'Human Resources'),
('mbrown', 'Michael', 'Brown', 'michael.brown@example.com', 'A', 'Engineering'),
('lgarcia', 'Linda', 'Garcia', 'linda.garcia@example.com', 'A', 'Customer Support'),
('rdavis', 'Richard', 'Davis', 'richard.davis@example.com', 'T', 'Sales'),
('bmiller', 'Barbara', 'Miller', 'barbara.miller@example.com', 'A', 'Research'),
('jwilson', 'James', 'Wilson', 'james.wilson@example.com', 'A', 'Engineering'),
('ajackson', 'Amanda', 'Jackson', 'amanda.jackson@example.com', 'I', 'Marketing'),
('dwhite', 'David', 'White', 'david.white@example.com', 'A', 'Finance'),
('smartinez', 'Sarah', 'Martinez', 'sarah.martinez@example.com', 'A', 'Human Resources'),
('tthomas', 'Thomas', 'Thomas', 'thomas.thomas@example.com', 'T', 'Engineering'),
('kharris', 'Karen', 'Harris', 'karen.harris@example.com', 'A', 'Customer Support'),
('canderson', 'Charles', 'Anderson', 'charles.anderson@example.com', 'A', 'Sales');
COMMIT;
